### ISSUE TITLE
Change requested for AppCenter: Close button position

### ISSUE THREAD

**Issue by danirabbit** [linuxhubit/catfacts#14]
Similar to https://github.com/linuxhubit/shouldidoit/issues/6

While reviewing your app, we noticed a change that needs to be made for it to be accepted.

It looks like you're manually packing a close button into the end of your titlebar. However, elementary OS uses close buttons at the start of the titlebar. Your app's close button should match this system behavior.

Once you've made this change, please create a new release and submit that to the AppCenter Dashboard. Thanks!

**Comment by cassidyjames** [comment]
@mirkobrombin can you prepare a 1.2.6 release so we can get this into AppCenter?

**Comment by mirkobrombin** [comment]
> @mirkobrombin can you prepare a 1.2.6 release so we can get this into AppCenter?

Yup, if the service APIs are back online
