### ISSUE TITLE
App doesn't seem to open

### ISSUE THREAD

**Issue by danirabbit** [linuxhubit/catfacts#15]
When trying to open Cat Facts, the app doesn't appear to open at all. Eventually after some time, a window appears with "API limit exceeded"

**Comment by mirkobrombin** [comment]
It worked before but now the APIs seem offline.

**Comment by cassidyjames** [comment]
@mirkobrombin this doesn't directly address the issue, but it may be worth shipping a handful of facts offline to fallback on in case of API issues.

**Comment by mirkobrombin** [comment]
> @mirkobrombin this doesn't directly address the issue, but it may be worth shipping a handful of facts offline to fallback on in case of API issues.

Good idea
